import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Lukeware Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1
          className={`
        h-screen 
        flex
        justify-center
        items-center 
        bg-gradient-to-r 
        from-green-500 
        to-blue-500`}
        >
          Hello world!
        </h1>
      </main>
    </>
  );
};

export default Home;
