import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/template/Layout";
import useAppData from "../data/hook/UseAppData";
import { MenuItemType } from "../types/Types";

export async function getStaticProps() {
  const resp = await fetch("http://localhost:3000/api/menus");
  const menuItens = await resp.json();
  return {
    revalidate: 3600,
    props: {
      menuItens,
    },
  };
}

const Home = (props: { menuItens: MenuItemType[] }) => {
  const { alterarTema } = useAppData();

  return (
    <>
      <Head>
        <title>Lukeware Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout
          titulo="Pagina inicial"
          subtitulo="Estamos construindo conteudo"
          menuItens={props.menuItens}
        >
          <button onClick={alterarTema}>Clique aqui</button>
        </Layout>
      </main>
    </>
  );
};

export default Home;
